## Industry rule for this stage

**Rule:** never modify or overwrite the raw source file. Load it read-only, explore it, and save any output under a new filename in `data/processed/` — the original raw CSV must always remain byte-identical so any stage can be re-run from scratch.

In [ ]:
import sys
sys.path.append("../")

from notebooks import *

In [ ]:
# load dataset
df = pd.read_csv("../data/raw/credit_risk_dataset.csv")

# Check Point 1 - Data Understanding

## Dataframe head

In [4]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [5]:
df['loan_status'].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

## Set the style for plot design

In [ ]:
def set_style():
    # apply base theme
    sns.set_style('darkgrid')

    # customize plot appearance
    sns.set(rc={
        "axes.facecolor": "#cce0ff",
        "figure.facecolor": "#cce0ff",
        "grid.color": "#D3D3D3",
        "text.color": "#000000",
        "font.size": 12,
        "axes.titlesize": 16
    })

    # set plotting context (controls scaling of labels, fonts, etc.)
    sns.set_context("notebook")

## Data Understanding

In [7]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [8]:
def basic_preprocessing(df):
    # check columns
    print("\nColumns of Dataframe : ")
    display(df.columns)
    print()

    # check shape
    print("\nShape of Dataframe : ")
    display(df.shape)
    print()

    # check info
    print("\nCheck Dataframe info : ")
    df.info()
    print()

    # Statistical Summary
    print("\nCheck the Statistical Summary of Dataframe : ")
    display(df.describe())
    print()

    # Statistical Summary of Categorical Features
    print("\nCheck the Categorical Features Statistical Summary of Dataframe : ")
    display(df.describe(include='object'))
    print()

    # show 5 rows
    print("\nShow Top 5 Rows of Dataframe : ")
    display(df.head())

In [9]:
basic_preprocessing(df)

Columns of Dataframe :

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_status', 'loan_percent_income',
       'cb_person_default_on_file', 'cb_person_cred_hist_length'],
      dtype='object')

Shape of Dataframe :

(32581, 12)

Check Dataframe info :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB


Check the Statistical Summary of Dataframe :

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

Check the Categorical Features Statistical Summary of Dataframe :

       person_home_ownership loan_intent loan_grade cb_person_default_on_file
count                  32581       32581      32581                     32581
unique                     4           6          7                         2
top                     RENT   EDUCATION          A                         N
freq                   16446        6453      10777                     26836

Show Top 5 Rows of Dataframe :

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

#### Rename the Df columns

In [10]:
# rename columns for consistency and readability
df = df.rename(columns={
    'person_age': 'Age',
    'person_income': 'Income',
    'person_home_ownership': 'Home_ownership',
    'person_emp_length': 'Employment_length',
    'loan_intent': 'Loan_intent',
    'loan_grade': 'internal_credit_rating',
    'loan_amnt': 'Loan_amount',
    'loan_int_rate': 'Interest_rate',
    'loan_status': 'Loan_status',
    'loan_percent_income': 'Loan_percent_income',
    'cb_person_default_on_file': 'Default',
    'cb_person_cred_hist_length': 'Credit_history_length'
})

#### Min and Max values in each columns

In [11]:
# function to display min and max values of all numeric columns
def show_min_max(df):
    for col in df.select_dtypes(include=['float64', 'int64']).columns:
        print(f"{col}: Min = {df[col].min()}, Max = {df[col].max()}")

In [12]:
show_min_max(df)

Age: Min = 20, Max = 144
Income: Min = 4000, Max = 6000000
Employment_length: Min = 0.0, Max = 123.0
Loan_amount: Min = 500, Max = 35000
Interest_rate: Min = 5.42, Max = 23.22
Loan_status: Min = 0, Max = 1
Loan_percent_income: Min = 0.0, Max = 0.83
Credit_history_length: Min = 2, Max = 30

## Clean dataframe

In [13]:
# function to clean dataframe and show before/after samples
def clean_dataframe(df):
    print("Before cleaning...\n")

    # show initial values of each column
    for col in df.columns:
        print(df[col].head())
        print()

    # clean categorical columns (string formatting)
    for col in df.columns:
        if df[col].dtype == 'O':
            df[col] = df[col].str.capitalize().str.replace(" ", "_")

    print("\nAfter cleaning...\n")

    # show cleaned values of each column
    for col in df.columns:
        print(df[col].head())
        print()

In [14]:
print("Converting the Upper case object column values into Capitalize\n")

clean_dataframe(df)

Converting the Upper case object column values into Capitalize

Before cleaning...

0    22
1    21
2    25
3    23
4    24
Name: Age, dtype: int64

0    59000
1     9600
2     9600
3    65500
4    54400
Name: Income, dtype: int64

0        RENT
1         OWN
2    MORTGAGE
3        RENT
4        RENT
Name: Home_ownership, dtype: object

0    123.0
1      5.0
2      1.0
3      4.0
4      8.0
Name: Employment_length, dtype: float64

0     PERSONAL
1    EDUCATION
2      MEDICAL
3      MEDICAL
4      MEDICAL
Name: Loan_intent, dtype: object

0    D
1    B
2    C
3    C
4    C
Name: internal_credit_rating, dtype: object

0    35000
1     1000
2     5500
3    35000
4    35000
Name: Loan_amount, dtype: int64

0    16.02
1    11.14
2    12.87
3    15.23
4    14.27
Name: Interest_rate, dtype: float64

0    1
1    0
2    1
3    1
4    1
Name: Loan_status, dtype: int64

0    0.59
1    0.10
2    0.57
3    0.53
4    0.55
Name: Loan_percent_income, dtype: float64

0    Y
1    N
2    N
3    N
4    Y
Name: Default, dtype: object

0    3
1    2
2    3
3    2
4    4
Name: Credit_history_length, dtype: int64


After cleaning...

0    22
1    21
2    25
3    23
4    24
Name: Age, dtype: int64

0    59000
1     9600
2     9600
3    65500
4    54400
Name: Income, dtype: int64

0        Rent
1         Own
2    Mortgage
3        Rent
4        Rent
Name: Home_ownership, dtype: object

0    123.0
1      5.0
2      1.0
3      4.0
4      8.0
Name: Employment_length, dtype: float64

0     Personal
1    Education
2      Medical
3      Medical
4      Medical
Name: Loan_intent, dtype: object

0    D
1    B
2    C
3    C
4    C
Name: internal_credit_rating, dtype: object

0    35000
1     1000
2     5500
3    35000
4    35000
Name: Loan_amount, dtype: int64

0    16.02
1    11.14
2    12.87
3    15.23
4    14.27
Name: Interest_rate, dtype: float64

0    1
1    0
2    1
3    1
4    1
Name: Loan_status, dtype: int64

0    0.59
1    0.10
2    0.57
3    0.53
4    0.55
Name: Loan_percent_income, dtype: float64

0    Y
1    N
2    N
3    N
4    Y
Name: Default, dtype: object

0    3
1    2
2    3
3    2
4    4
Name: Credit_history_length, dtype: int64

Observation : Employment_length has all integer values with float type (5 -> 5.0) so we will convert it into integer

In [15]:
# convert employment length column to integer type (nullable Int64)
df['Employment_length'] = df['Employment_length'].astype('Int64')

In [16]:
# Save (industry common formats)
df.to_csv("../data/processed/df.csv", index=False)